import Head from "next/head";
import styles from "@/styles/Home.module.css";
import {useState, useCallback } from "react";
import Label from '../components/Label.js';
import Canvas from '../components/Canvas.js';

export default function Home() {
  const [circles, setCircles] = useState([]);

  const addCircle = useCallback((newCircle) => {
    setCircles((prevCircles) => [...prevCircles, { ...newCircle, text: "" }]);
  }, []);

  const deleteCircle = useCallback((id) => {
    setCircles((prevCircles) => prevCircles.filter((circle) => circle.id !== id));
  }, []);

  const updateCircle = useCallback((id, newX, newY) => {
    setCircles((prevCircles) =>
        prevCircles.map((circle) =>
            circle.id === id ? { ...circle, labelX: newX, labelY: newY } : circle
        )
    );
  }, []);

  const updateCircleText = useCallback((id, newText) => {
    setCircles((prevCircles) =>
        prevCircles.map((circle) =>
            circle.id === id ? { ...circle, text: newText } : circle
        )
    );
  }, []);

  return (
      <>
        <Head>
          <title>Four Quadrants</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={`${styles.page}`}>
            <div className="toolbar">
                <ul>
                    <li>upload image</li>
                    <li>save</li>
                    <li>share</li>
                </ul>

            </div>

            <main className={styles.main}>

            <div className={styles.quad} style={{ position: 'relative', width: '600px', height: '600px' }}>
                <input
                    type="text"
                    style={{
                        position: 'absolute',
                        left: '50%',
                        top: '-30px',
                        transform: 'translateX(-50%)',
                        margin: '5px',
                    }}
                />
                <input
                    type="text"
                    style={{
                        position: 'absolute',
                        left: '-80px',
                        top: '50%',
                        transform: 'rotate(-90deg) translateY(-50%)',
                        margin: '5px',
                    }}
                />
                <input
                    type="text"
                    style={{
                        position: 'absolute',
                        right: '-80px',
                        top: '50%',
                        transform: 'rotate(90deg) translateY(-50%)',
                        margin: '5px',
                    }}
                />
                <input
                    type="text"
                    style={{
                        position: 'absolute',
                        left: '50%',
                        bottom: '-30px',
                        transform: 'translateX(-50%)',
                        margin: '5px',
                    }}
                />

              <Canvas
                  circles={circles}
                  onAddCircle={addCircle}
                  onDeleteCircle={deleteCircle}
                  onUpdateCircle={updateCircle}
              />

              <div style={{ position: 'absolute', top: 0, left: 0 }}>
                {circles.map((circle) => (
                    <Label
                        key={circle.id}
                        id={circle.id}
                        x={circle.labelX}
                        y={circle.labelY}
                        value={circle.text}
                        onUpdateText={updateCircleText}
                        onDelete={() => deleteCircle(circle.id)}
                        onDragStop={updateCircle}
                    />
                ))}

              </div>
            </div>
          </main>
        </div>
      </>
  );
}
